Turkish = {
    "select_action": "Yapmak istediğiniz işlemi seçiniz:",
    "enter_withdrawal_amount": "Çekmek istediğiniz miktarı giriniz:",
    "enter_deposit_amount": "Yatırmak istediğiniz miktarı giriniz:",
    "menu_closing": "Menü kapatılıyor...",
    "login_success": "Giriş başarılı. Hoşgeldin",
    "your_balance": "Bakiyeniz:",
    "login_failed": "Giriş başarısız. Lütfen bilgilerinizi kontrol edin.",
    "enter_username": "Kullanıcı adınızı giriniz:",
    "enter_password": "Şifrenizi giriniz:",
    "username_taken": "Kullanıcı adı daha önceden alınmış. Lütfen başka bir kullanıcı adı giriniz: ",
    "registration_success": "Kayıt başarılı",
    "deposit_required": "İşlem yapabilmek için para yatırınız.",
    "welcome_message": "ÇÜ Bankası'na hoşgeldiniz. Lütfen yapmak istediğiniz işlemi seçiniz",
    "login": "1-Giriş yap",
    "register": "2-Kayıt ol",
    "toggle_language": "3-Change language to english",
    "logout": "0-Çıkış yap",
    "language_change_not_implemented": "Dil değiştirme işlevi henüz eklenmemiştir.",
    "invalid_choice": "Geçersiz seçim. Tekrar deneyiniz!",
    "invalid_operation": "Geçersiz işlem. Yeniden deneyiniz.",
    "invalid_numeric_value": "Sen harfle mi miktar belirtiyorsun🤨. Sana ceza olarak yapmak istediğin işlemi bir daha seçtiriyorum.",
    "money1": "1-Para Çek",
    "money2": "2-Para Yatır",
    "money3": "0- Menüyü Kapat",
    "a": "Çekmek istediğiniz tutar bakiyenizden fazla olamaz.",
    "b": "Lütfen sayı giriniz.",
    "c": "Giriş yapınız.",
    "d": "Çıkış yapılıyor...",
    "e": "Böyle bir seçenek yok tekrar seçim yapınız!",
    "german": "5-Sprache auf Deutsch ändern",
    "italian": "4-Cambia la lingua in italiano",
    "turk": "6-Dili Türkçe olarak değiştir",
    "k" : "Dil zaten Türkçe",
    "faiz": "3-Faiz İşlemleri",
    "faiz2" : """Paranızı kaç aylık faize yatırmak istiyorsunuz? 
                    1- 3 Ay
                    2- 6 Ay
                    3- 12 Ay
                    4- 24 Ay
                    5- 36 Ay
                    :""",
    "faiz3" : "Faize yatırmak istediğiniz miktarı giriniz: ",
    "name": "Adınız:",
    "surname": "Soyadınız:",
    "kredi" : "4-Kredi İşlemleri",
    "kredi_menu": "1- Kredi Sorgula\n2- Kredi Al\n3- Kredi borcunu öde\n0-Menüye dön\n:",
    "existing_credit_warning": "Zaten bir krediniz var. Önce mevcut krediyi ödemelisiniz.",
    "money_transfer" : "5-Para Transfer",
    "no_kredi": "Kredi alamazsınız. Daha önceden aldığınız krediyi ödemediniz.",
    "ask" : "Para göndermeye devam etmek ister misiniz? (E/h) :",
    "reciever": "Parayı göndermek istediğiniz kişinin kullanıcı adını giriniz: ",
    "not_found": "Böyle bir kullanıcı bulunamadı.",
    "send": "Göndermek istediğiniz miktari giriniz: ",
    "send2": "Bakiyenizden daha fazla miktar gönderemezsiniz.",
    "error_balance": "Bakiye güncelleme hatası:",
    "kredi0": "Ödenmesi gereken bir kredi bulunmuyor.",
    "kredi1" : "Kredi borcunuzun ödeyeceğiniz kadar olan miktarı giriniz: ",
    "kredi2": "Ödemek istediğiniz tutar bakiyeden büyük olamaz.",
    "kredi3": "Kredi ödeme işlemi başarılı. Yeni bakiye:",
    "kredi4": "Kalan kredi borcu:",
    "kredi5": "Almak istediğiniz kredi miktarını giriniz: ",
    "hata": "Hata oluştu:",
    "kredi6": "Kaç ay sonra ödeme yapacaksınız?\n0- 3 AY\n1- 6 AY\n2- 12 AY\n3- 24 AY\n4- 36 AY\nSeçiminiz: ",
    "kredi7": "Kredi başarıyla alındı. Yeni bakiye: ",
    "kredi8": "Yeni kredi borcu:",
    "h": "H",
    "kumar": "Bahse yatırmak istediğiniz miktarı giriniz: ",
    "kumar2": "Bahse yatırmak istediğiniz tutar bakiyenizden fazla olamaz.",
    "kumar3": "Zar atılacak. Lütfen tahmininizi giriniz(1-6):",
    "kumar4": "Zar atılıyor...",
    "kumar5": "Tebrikler kazandınız.Yeni bakiyeniz:",
    "kumar6": "Oynamaya devam etmek ister misiniz(E/h) : ",
    "kumar7": "Bahsi kaybettiniz.",
    "kumar8": "Tekrar denemek istermisiniz(E/h) : ",
    "kumar_menu": "6-Şans Oyunları(Şimdilik sadece zar atma var.)",
    "komisyon": "%10 komisyonu ödeyecek bakiyeniz yok.",
    "komisyonuyarı": "Para transfer işlemlerinde göndereceğiniz miktarın %10 kadarını komisyon olarak ödeyeceksiniz",
    "dice": "Zar sonucu:",
    "dicenum": "Geçersiz tahmin. Lütfen [1,2,3,4,5,6] sayılarından birini seçin.",
    "date": "Tarih:",
    "time": "Saat:",
    "doviz": "7-Döviz İşlemleri",
    "doviz_menu": "1-Döviz hesabı aç",
    "dolaracc": "1-Dolar hesabı aç",
    "euracc": "2-Euro hesabı aç",
    "menu_exit": "0-Menüden çık",
    "alreadyacc": "Böyle bir hesabınız zaten var.",
    "changemoney": "11-Parabirimi değiştir",
    "faiz_a": "Faize yarımak istediğiniz miktar bakiyenizden fazla olamaz.",
    "delete_acc": "8-Hesap sil",
    "change_pass": "9-Parolanı değiştir",
    "tutarfazla": "Bankamızdan bu meblada kredi çekemezsiniz. Çekebileceğiniz en yüksek miktar : ",
    "dolarhesap": "Dolar hesabınız başarıyla açıldı.",
    "eurohesap": "EURO hesabınız başarıyla açıldı.",
    "hataligiris": "Hatalı giriş yaptınız lütfen tekrar deneyniz.",
    "choicedelete": "Silmek istediğiniz hesabı seçin(TRY hesabınızı silemezsiniz.) (DOLAR(usd)/EURO(eur)) (Dilinizde böyle bir kelime olmasada büyük harflerle yazılmış olanı yazın):",
    "yanlistus": "Yanlış tuşlama yaptınız lütfen belirtilen hesaplardan birini seçin.",
    "trykarşılık": "Silmek istediğiniz hesapta para varsa TRY karşılığı TRY hesabınıza eklenecektir.",
    "başarılısilme": "Hesabınız başarıyla silindi.",
    "newPass": "Yeni parolanızı giriniz:",
    "newPassCheck": "Parolanızı doğrulayın:",
    "secure": "Güvenlik sebebiyle tekrardan giriş yapmanız gerek.",
    "parolauyuşmuyor": "Parolalar uyuşmuyor lütfen tekrar deneyiniz.",
    "usdAccNotFound": "Dolar hesabınız bulunmamaktadır.",
    "eurAccNotFound": "EURO hesabınız bulunmamaktadır",
    "moneyinput": "İşlem yapmak istediğiniz para birimini seçiniz(TRY/USD/EUR) (Hesabınızın bulunmadığı para birimini seçerseniz o para birimine ait bir hesap oluşturulur): ",
    "dolarhesapyok": "Bu kullanıcının USD hesabı bulunmuyor.",
    "eurohesapyok": "Bu kullanıcının EUR hesabı bulunmuyor.",
    "whicacc": "Hangi hesabınıza para göndermek istiyorsunuz",
    "urnousdacc": "USD hesabınız bulunmuyor.",
    "usdkarşılık": "Göndereceğiniz miktar güncel kur üzerinden hesaplanıp USD karşılığı hesabınıza aktarılacaktır.",
    "urnoeuracc": "EUR hesabınız bulunmuyor.",
    "eurkarşılık": "Göndereceğiniz miktar güncel kur üzerinden hesaplanıp EUR karşılığı hesabınıza aktarılacaktır.",
    "tlkarşılık": "Göndereceğiniz miktar güncel kur üzerinden hesaplanıp TRY karşılığı hesabınıza aktarılacaktır",
    "sameacc": "Aynı hesaba para gönderim yapamazsınız.",
    "uhavent": "Böyle bir hesabınız bulunmuyor.",
    "rhesap": "Alıcının hangi hesabına para göndermek istersiniz?(TRY/USD/EUR) | !EĞER SEÇECEĞİNİZ HESAP ŞU AN İŞLEM YAPTIĞINIZ PARA BİRİMİ İLE AYNI HESAP İSE 'ENTER' TUŞLAYINIZ! :",
    "rusdno": "Alıcının USD hesabı bulunmuyor.",
    "rnoeur": "Alıcnın EUR hesabı bulunmuyor."




}

English = {
    "select_action": "Please select the action you want to perform:",
    "enter_withdrawal_amount": "Enter the amount you want to withdraw:",
    "enter_deposit_amount": "Enter the amount you want to deposit:",
    "menu_closing": "Menu is closing...",
    "login_success": "Login successful. Welcome",
    "your_balance": "Your balance:",
    "login_failed": "Login failed. Please check your details.",
    "enter_username": "Enter your username:",
    "enter_password": "Enter your password:",
    "username_taken": "Username is already taken. Please choose another username:",
    "registration_success": "Registration successful",
    "deposit_required": "Please deposit money to perform transactions.",
    "welcome_message": "Welcome to CU Bank. Please select the action you want to perform:",
    "login": "1-Log in",
    "register": "2-Register",
    "toggle_language": "3-Change language to english",
    "logout": "0-Log out",
    "language_change_not_implemented": "Language change function has not been implemented yet.",
    "invalid_choice": "Invalid choice. Please try again!",
    "invalid_operation": "Invalid operation. Please try again.",
    "invalid_numeric_value": "Invalid input. Please enter a numeric value.",
    "money1": "1-Withdraw money",
    "money2": "2-Deposit money",
    "money3": "0- Close menu",
    "a": "The amount you want to withdraw cannot exceed your balance.",
    "b": "Please enter a number.",
    "c": "Sign in",
    "d": "Exiting...",
    "e": "This is not an option, please choose again!",
    "german": "5-Sprache auf Deutsch ändern",
    "italian": "4-Cambia la lingua in italiano",
    "turk": "6-Dili Türkçe olarak değiştir",
    "k" : "The language is already english ",
    "faiz" : "3-Interest Transactions",
    "faiz2" : """How many months of interest do you want to invest your money? 
                    1- 3 Months
                    2- 6 Months
                    3- 12 Months
                    4- 24 Months
                    5- 36 Months
                    :""",
    "faiz3" : "Enter the amount you want to invest in interest:",
    "name": "Your name:",
    "surname": "Your surname:",
    "existing_credit_warning": "You already have a credit. You need to pay off the existing credit first.",
    "money_transfer" : "5-Money Transfer",
    "ask":"Do you want to continue sending money?(Y/n) :",
    "reciever": "Enter the username of the person you want to send the money to: ",
    "not_found": "No such user found.",
    "send": "Enter the amount you want to send: ",
    "send2": "You cannot send more than your balance. ",
    "error_balance": "Balance update error:",
    "kredi0": "There are no loans to be repaid.",
    "kredi1" : "Enter the amount of your loan that you will repay: ",
    "kredi2": "The amount you want to pay cannot be greater than the balance.",
    "kredi3": "Loan payment successful. New balance:",
    "kredi4": "Remaining loan debt:",
    "kredi5": "Enter the amount of credit you wish to receive: ",
    "hata": "Error occurred:",
    "kredi6": "After how many months will you pay? \n0- 3 months\n1- 6 months\n2- 12 months\n3- 24 months\n4- 36 months\nYour choice: ",
    "kredi7": "Loan received successfully. New balance: ",
    "kredi8" : "New loan debt:",
    "kredi" : "4-Credit Transactions",
    "kredi_menu": "1- Inquire Loan\n2- Get Loan\n3- Pay Loan\n0-Return to menu\n:",
    "h": "N",
    "kumar": "Enter the amount you want to bet: ",
    "kumar2": "The amount you want to bet cannot be more than your balance.",
    "kumar3": "Dice will be thrown. Please enter your guess (1-6):",
    "kumar4": "Rolling the dice...",
    "kumar5": "Congratulations, you've won. Your new balance:",
    "kumar6": "Do you want to continue playing (Y/n): ",
    "kumar7": "You lost the bet.",
    "kumar8": "Would you like to try again (Y/n): ",
    "kumar_menu": "6-Games of Chance (For now there is only dice rolling.)",
    "no_kredi": "You cannot get a loan. You have defaulted on a previous loan.",
    "komisyon": "You don't have the funds to pay the 10% commission.",
    "komisyonuyarı" : "In money transfer transactions, you will pay 10% of the amount you send as commission",
    "dice": "Dice result:",
    "dicenum": "Invalid guess. Please select one of the numbers [1,2,3,4,5,6].",
    "date": "Date:",
    "time": "Time:",
    "doviz": "7-Foreign Exchange Transactions",
    "doviz_menu": "1-Open a foreign exchange account",
    "dolaracc": "1-Open a dollar account",
    "euracc": "2-Open a euro account",
    "menu_exit": "0-Exit menu",
    "alreadyacc": "You already have such an account.",
    "changemoney": "11-Change currency",
    "faiz_a": "The amount you wish to deposit into interest cannot exceed your balance.",
    "delete_acc": "8-Delete account",
    "change_pass": "9-Change your password",
    "tutarfazla": "You cannot borrow this amount from our bank. The maximum amount you can borrow is: ",
    "dolarhesap": "Your USD account has been successfully opened.",
    "eurohesap": "Your EURO account has been successfully opened.",
    "hataligiris": "You made an incorrect entry, please try again.",
    "choicedelete": "Select the account you want to delete (you cannot delete your TRY account). (DOLAR(USD)/EURO(EUR)) (Even if there isn't a word for this in your language, type the one in uppercase):",
    "yanlistus": "You made an incorrect button press, please select one of the specified accounts.",
    "trykarşılık": "If there is money in the account you want to delete, it will be added to your TRY account at its TRY equivalent.",
    "başarılısilme": "Your account has been successfully deleted.",
    "newPass": "Enter your new password:",
    "newPassCheck": "Confirm your password:",
    "secure": "For security reasons, you need to log in again.",
    "parolauyuşmuyor": "Passwords do not match, please try again.",
    "usdAccNotFound": "Your USD account does not exist.",
    "eurAccNotFound": "Your EURO account does not exist.",
    "moneyinput": "Select the currency you wish to process (TRY/USD/EUR) (If you select a currency you do not have, an account will be created for that currency):",
    "dolarhesapyok": "This user does not have a USD account.",
    "eurohesapyok": "This user does not have an EUR account.",
    "whicacc": "Which account would you like to send money to?",
    "urnousdacc": "You do not have a USD account.",
    "usdkarşılık": "The amount you send will be calculated and transferred to your account in USD equivalent based on the current exchange rate.",
    "urnoeuracc": "You do not have an EUR account.",
    "eurkarşılık": "The amount you send will be calculated and transferred to your account in EUR equivalent based on the current exchange rate.",
    "tlkarşılık": "The amount you send will be calculated and transferred to your account in TRY equivalent based on the current exchange rate.",
    "sameacc": "You cannot send money to the same account.",
    "uhavent": "You do not have such an account.",
    "rhesap": "Which account would you like to send money to? (TRY/USD/EUR) | !IF THE ACCOUNT YOU SELECT IS THE SAME AS THE CURRENCY YOU ARE CURRENTLY PROCESSING, PRESS 'ENTER'!:",
    "rusdno": "The recipient does not have a USD account.",
    "rnoeur": "The recipient does not have an EUR account."
}


Italian = {
    "select_action": "Si prega di selezionare l'azione che si desidera eseguire:",
    "enter_withdrawal_amount": "Inserisci l'importo che vuoi prelevare:",
    "enter_deposit_amount": "Inserisci l'importo che vuoi depositare:",
    "menu_closing": "Il menu si sta chiudendo...",
    "login_success": "Accesso effettuato con successo. Benvenuto",
    "your_balance": "Il tuo saldo:",
    "login_failed": "Accesso non riuscito. Si prega di controllare i dettagli.",
    "enter_username": "Inserisci il tuo nome utente:",
    "enter_password": "Inserisci la tua password:",
    "username_taken": "Nome utente già in uso. Si prega di scegliere un altro nome utente:",
    "registration_success": "Registrazione avvenuta con successo",
    "deposit_required": "Si prega di depositare denaro per effettuare transazioni.",
    "welcome_message": "Benvenuto alla Banca CU. Si prega di selezionare l'azione che si desidera eseguire:",
    "login": "1-Accedi",
    "register": "2-Registrati",
    "toggle_language": "3-Change language to english",
    "logout": "0-Disconnetti",
    "language_change_not_implemented": "La funzione di cambio lingua non è ancora stata implementata.",
    "invalid_choice": "Scelta non valida. Per favore riprova!",
    "invalid_input_number_only": "Per favore inserisci un numero.",
    "invalid_operation": "Operazione non valida. Per favore riprova.",
    "invalid_numeric_value": "Input non valido. Per favore inserisci un valore numerico.",
    "money1": "1-Prelevare denaro",
    "money2": "2-Deposita denaro",
    "money3": "0-Chiudi menu",
    "a": "L'importo che si desidera prelevare non può superare il saldo.",
    "b": "Per favore inserisci un numero.",
    "c": "Accedi",
    "d": "Uscita...",
    "e": "Questa non è un'opzione, la preghiamo di scegliere di nuovo!",
    "german": "5-Sprache auf Deutsch ändern",
    "italian": "4-Cambia la lingua in italiano",
    "turk": "6-Dili Türkçe olarak değiştir",
    "k": "la lingua è già italiana",
    "faiz": "3-Transazioni di interesse",
    "faiz2" : """Per quanti mesi di interessi volete investire il vostro denaro? 
                    1- 3 mesi
                    2- 6 mesi
                    3- 12 mesi
                    4- 24 mesi
                    5- 36 mesi
                    :""",
    "faiz3" : "Inserire l'importo che si desidera investire in interessi: ",
    "name" : "Il tuo nome: ",
    "surname": "Il vostro cognome: ",
    "money_transfer": "5-Trasferimento di denaro",
    "ask": "Volete continuare a inviare denaro? (S/c) :",
    "reciever": "Inserite il nome utente della persona a cui volete inviare il denaro: ",
    "not_found": "Nessun utente trovato.",
    "send" : "Inserire l'importo che si desidera inviare: ",
    "send2": "Non è possibile inviare più del proprio saldo. ",
    "error_balance": "Errore di aggiornamento del bilancio:",
    "kredi0": "Non ci sono prestiti da rimborsare.",
    "kredi1": "Inserire l'importo del debito del prestito che si intende rimborsare: ",
    "kredi2": "L'importo da pagare non può essere superiore al saldo.",
    "kredi3" : "Pagamento del credito riuscito. Nuovo saldo:",
    "kredi4": "Debito residuo del prestito:",
    "kredi5": "Inserire l'importo del prestito che si desidera ricevere: ",
    "hata": "Si è verificato un errore:",
    "kredi6": "Dopo quanti mesi pagherà? \n0- 3 mesi\n1- 6 mesi\n2- 12 mesi\n3- 24 mesi\n4- 36 mesi\nLa scelta è sua: ",
    "kredi7": "Prestito ricevuto con successo. Nuovo saldo: ",
    "kredi8": "Nuovo debito di prestito:",
    "kredi": "4-Operazioni di credito",
    "kredi_menu": "1- Chiedere un prestito\n2- Ottenere un prestito\n3- Pagare il debito del prestito\n0- Tornare al menu\n:",
    "h": "C",
    "kumar": "Inserire l'importo che si desidera scommettere:",
    "kumar2:": "L'importo che si vuole scommettere non può essere superiore al proprio saldo.",
    "kumar3": "I dadi saranno lanciati. Inserite la vostra ipotesi (da 1 a 6):",
    "kumar4": "Lancio dei dadi...",
    "kumar5": "Congratulazioni, avete vinto. Il vostro nuovo equilibrio:",
    "kumar6": "Volete continuare a giocare (S/c) : ",
    "kumar7": "Hai perso la scommessa.",
    "kumar8": "Vuole riprovare (S/c): ",
    "kumar_menu": "6-Giochi d'azzardo (per ora c'è solo il lancio di dadi).",
    "no_kredi": "Non è possibile ottenere un prestito. Siete inadempienti rispetto a un precedente prestito.",
    "komisyon": "Non avete i fondi per pagare la commissione del 10%.",
    "komisyonuyarı": "Nelle transazioni di trasferimento di denaro, pagherete il 10% dell'importo inviato come commissione.",
    "dice": "Risultato dei dadi:",
    "dicenum": "Indovinello non valido. Selezionare uno dei numeri [1,2,3,4,5,6].",
    "date": "La storia:",
    "time": "Tempo:",
    "doviz": "7-Operazioni in valuta estera",
    "doviz_menu": "1-Apri un conto in valuta estera",
    "dolaracc": "1-Apri un conto in dollari",
    "euracc": "2-Apri un conto in euro",
    "menu_exit": "0-Esci dal menu",
    "alreadyacc": "Hai già un conto del genere.",
    "changemoney": "11-Cambia valuta",
    "faiz_a": "L'importo che desideri depositare a interesse non può superare il tuo saldo.",
    "delete_acc": "8-Elimina account",
    "change_pass": "9-Cambia la tua password",
    "tutarfazla": "Non puoi prendere in prestito questa somma dalla nostra banca. L'importo massimo che puoi prendere in prestito è: ",
    "dolarhesap": "Il tuo conto USD è stato aperto con successo.",
    "eurohesap": "Il tuo conto EURO è stato aperto con successo.",
    "hataligiris": "Hai effettuato un ingresso errato, per favore riprova.",
    "choicedelete": "Seleziona l'account che desideri eliminare (non puoi eliminare il tuo account TRY). (DOLAR(USD)/EURO(EUR)) (Anche se non esiste una parola per questo nella tua lingua, digita quella in maiuscolo):",
    "yanlistus": "Hai premuto un tasto errato, per favore seleziona uno dei conti specificati.",
    "trykarşılık": "Se ci sono soldi nell'account che desideri eliminare, verranno aggiunti al tuo account TRY al loro equivalente in TRY.",
    "başarılısilme": "Il tuo account è stato eliminato con successo.",
    "newPass": "Inserisci la tua nuova password:",
    "newPassCheck": "Conferma la tua password:",
    "secure": "Per motivi di sicurezza, devi accedere di nuovo.",
    "parolauyuşmuyor": "Le password non corrispondono, per favore riprova.",
    "usdAccNotFound": "Il tuo account USD non esiste.",
    "eurAccNotFound": "Il tuo account EURO non esiste.",
    "moneyinput": "Seleziona la valuta con cui desideri effettuare l'operazione (TRY/USD/EUR) (Se selezioni una valuta che non possiedi, verrà creato un account per quella valuta):",
    "dolarhesapyok": "Questo utente non ha un account USD.",
    "eurohesapyok": "Questo utente non ha un account EUR.",
    "whicacc": "A quale account desideri inviare denaro?",
    "urnousdacc": "Non hai un account USD.",
    "usdkarşılık": "L'importo che invii verrà calcolato e trasferito al tuo account in USD equivalente in base al tasso di cambio attuale.",
    "urnoeuracc": "Non hai un account EUR.",
    "eurkarşılık": "L'importo che invii verrà calcolato e trasferito al tuo account in EUR equivalente in base al tasso di cambio attuale.",
    "tlkarşılık": "L'importo che invii verrà calcolato e trasferito al tuo account in TRY equivalente in base al tasso di cambio attuale.",
    "sameacc": "Non puoi inviare denaro allo stesso account.",
    "uhavent": "Non hai un account del genere.",
    "rhesap": "A quale account desideri inviare denaro? (TRY/USD/EUR) | !SE L'ACCOUNT CHE SELEZIONI È LO STESSO DELLA VALUTA CHE STAI ATTUALMENTE PROCESSANDO, PREMI 'ENTER'!:",
    "rusdno": "Il destinatario non ha un account USD.",
    "rnoeur": "Il destinatario non ha un account EUR."
}


German = {
    "select_action": "Bitte wählen Sie die gewünschte Aktion aus:",
    "enter_withdrawal_amount": "Geben Sie den Betrag ein, den Sie abheben möchten:",
    "enter_deposit_amount": "Geben Sie den Betrag ein, den Sie einzahlen möchten:",
    "menu_closing": "Das Menü wird geschlossen...",
    "login_success": "Anmeldung erfolgreich. Willkommen",
    "your_balance": "Ihr Kontostand:",
    "login_failed": "Anmeldung fehlgeschlagen. Bitte überprüfen Sie Ihre Angaben.",
    "enter_username": "Geben Sie Ihren Benutzernamen ein:",
    "enter_password": "Geben Sie Ihr Passwort ein:",
    "username_taken": "Benutzername ist bereits vergeben. Bitte wählen Sie einen anderen Benutzernamen:",
    "registration_success": "Registrierung erfolgreich",
    "deposit_required": "Bitte zahlen Sie Geld ein, um Transaktionen durchzuführen.",
    "welcome_message": "Willkommen bei CU Bank. Bitte wählen Sie die gewünschte Aktion aus:",
    "login": "1-Anmelden",
    "register": "2-Registrieren",
    "toggle_language": "3-Change language to english",
    "logout": "0-Abmelden",
    "language_change_not_implemented": "Die Sprachwechselfunktion wurde noch nicht implementiert.",
    "invalid_choice": "Ungültige Auswahl. Bitte versuchen Sie es erneut!",
    "invalid_input_number_only": "Bitte geben Sie eine Zahl ein.",
    "invalid_operation": "Ungültige Operation. Bitte versuchen Sie es erneut.",
    "invalid_numeric_value": "Ungültige Eingabe. Bitte geben Sie einen numerischen Wert ein.",
    "money1": "1-Geld abheben",
    "money2": "2-Geld einzahlen",
    "money3": "0-Menü schließen",
    "a": "Der Betrag, den Sie abheben möchten, darf Ihren Kontostand nicht überschreiten.",
    "b": "Bitte geben Sie eine Zahl ein.",
    "c": "Anmelden",
    "d": "Beenden...",
    "e": "Das ist keine Option, bitte wählen Sie erneut!",
    "german": "5-Sprache auf Deutsch ändern",
    "italian": "4-Cambia la lingua in italiano",
    "turk": "6-Dili Türkçe olarak değiştir",
    "k": "die Sprache ist bereits deutsch",
    "faiz": "3-Zins-Transaktionen",
    "faiz2": """Wie viele Zinsmonate wollen Sie Ihr Geld anlegen? 
                    1- 3 Monate
                    2- 6 Monate
                    3- 12 Monate 
                    4- 24 Monate
                    5- 36 Monate
                    :""",
    "faiz3": "Geben Sie den Betrag ein, den Sie in Zinsen investieren wollen:",
    "name" : "Ihr Name: ",
    "surname": "Ihr Nachname: ",
    "money_transfer": "5-Geldtransfer",
    "ask" : "Wollen Sie weiterhin Geld schicken? (J/n) :",
    "reciever": "Geben Sie den Benutzernamen der Person ein, an die Sie das Geld senden möchten: ",
    "not_found": "Kein solcher Benutzer gefunden.",
    "send": "Geben Sie den Betrag ein, den Sie senden möchten: ",
    "send2": "Sie können nicht mehr als Ihr Guthaben senden. ",
    "error_balance": "Fehler bei der Aktualisierung der Bilanz:",
    "kredi0": "Es müssen keine Kredite zurückgezahlt werden.",
    "kredi1": "Geben Sie den Betrag Ihrer Darlehensschuld an, den Sie zurückzahlen werden: ",
    "kredi2": "Der Betrag, den Sie zahlen möchten, darf nicht höher sein als der Saldo.",
    "kredi3" : "Kreditauszahlung erfolgreich. Neues Guthaben:",
    "kredi4": "Verbleibende Darlehensschulden:",
    "kredi5": "Geben Sie den Darlehensbetrag ein, den Sie erhalten möchten: ",
    "hata": "Ein Fehler ist aufgetreten:",
    "kredi6": "Nach wie vielen Monaten werden Sie zahlen? \n0- 3 Monate\n1- 6 Monate\n2- 12 Monate\n3- 24 Monate\n4- 36 Monate\nIhre Entscheidung: ",
    "kredi7": "Darlehen erfolgreich erhalten. Neuer Saldo: ",
    "kredi8": "Neue Darlehensschulden:",
    "kredi": "4-Kredit-Transaktionen",
    "kredi_menu": "1- Kredit anfragen\n2- Kredit erhalten\n3- Kreditschulden bezahlen\n0-zurück zum Menü\n:",
    "h": "N",
    "kumar": "Geben Sie den Betrag ein, den Sie setzen möchten:",
    "kumar2:": "Der Betrag, den Sie setzen möchten, kann nicht höher sein als Ihr Guthaben.",
    "kumar3": "Der Würfel wird geworfen. Bitte geben Sie Ihren Tipp ein (1-6):",
    "kumar4": "Die Würfel rollen...",
    "kumar5": "Herzlichen Glückwunsch, Sie haben gewonnen: Ihr neues Gleichgewicht:",
    "kumar6": "Möchten Sie weiterspielen (J/n) : ",
    "kumar7": "Sie haben die Wette verloren.",
    "kumar8": "Möchten Sie es noch einmal versuchen (J/n): ",
    "kumar_menu": "6-Games of Chance (Im Moment wird nur gewürfelt.)",
    "no_kredi": "Sie bekommen keinen Kredit. Sie sind mit einem früheren Kredit in Verzug geraten.",
    "komisyon": "Sie haben nicht die Mittel, um die 10%ige Provision zu zahlen.",
    "komisyonuyarı": "Bei Geldtransfers zahlen Sie 10 % des von Ihnen gesendeten Betrags als Provision.",
    "dice": "Würfelergebnis:",
    "dicenum": "Ungültig erraten. Bitte wählen Sie eine der Zahlen [1,2,3,4,5,6].",
    "date": "Geschichte:",
    "time": "Zeit:",
    "doviz": "7-Devisengeschäfte",
    "doviz_menu": "1-Devisenkonto eröffnen",
    "dolaracc": "1-Dollar-Konto eröffnen",
    "euracc": "2-Euro-Konto eröffnen",
    "menu_exit": "0-Menü verlassen",
    "alreadyacc": "Ein solches Konto haben Sie bereits.",
    "changemoney": "11-Währungswechsel",
    "faiz_a": "Der Betrag, den Sie in Zinsen anlegen möchten, darf Ihr Guthaben nicht überschreiten.",
    "delete_acc": "8-Konto löschen",
    "change_pass": "9-Passwort ändern",
    "tutarfazla": "Sie können diesen Betrag nicht bei unserer Bank leihen. Der Höchstbetrag, den Sie leihen können, ist: ",
    "dolarhesap": "Ihr USD-Konto wurde erfolgreich eröffnet.",
    "eurohesap": "Ihr EURO-Konto wurde erfolgreich eröffnet.",
    "hataligiris": "Sie haben einen Fehler gemacht, bitte versuchen Sie es erneut.",
    "choicedelete": "Wählen Sie das Konto aus, das Sie löschen möchten (Ihr TRY-Konto kann nicht gelöscht werden). (DOLAR(USD)/EURO(EUR)) (Auch wenn es dafür kein Wort in Ihrer Sprache gibt, geben Sie das in Großbuchstaben Geschriebene ein):",
    "yanlistus": "Sie haben einen falschen Knopf gedrückt, bitte wählen Sie eines der angegebenen Konten aus.",
    "trykarşılık": "Falls Geld auf dem Konto vorhanden ist, das Sie löschen möchten, wird es zum TRY-Gegenwert Ihrem TRY-Konto hinzugefügt.",
    "başarılısilme": "Ihr Konto wurde erfolgreich gelöscht.",
    "newPass": "Geben Sie Ihr neues Passwort ein:",
    "newPassCheck": "Bestätigen Sie Ihr Passwort:",
    "secure": "Aus Sicherheitsgründen müssen Sie sich erneut anmelden.",
    "parolauyuşmuyor": "Die Passwörter stimmen nicht überein, bitte versuchen Sie es erneut.",
    "usdAccNotFound": "Ihr USD-Konto existiert nicht.",
    "eurAccNotFound": "Ihr EURO-Konto existiert nicht.",
    "moneyinput": "Wählen Sie die Währung aus, mit der Sie die Transaktion durchführen möchten (TRY/USD/EUR) (Wenn Sie eine Währung auswählen, die Sie nicht haben, wird ein Konto für diese Währung erstellt):",
    "dolarhesapyok": "Dieser Benutzer hat kein USD-Konto.",
    "eurohesapyok": "Dieser Benutzer hat kein EUR-Konto.",
    "whicacc": "Auf welches Konto möchten Sie Geld senden?",
    "urnousdacc": "Sie haben kein USD-Konto.",
    "usdkarşılık": "Der Betrag, den Sie senden, wird berechnet und Ihrem Konto im USD-Gegenwert entsprechend dem aktuellen Wechselkurs gutgeschrieben.",
    "urnoeuracc": "Sie haben kein EUR-Konto.",
    "eurkarşılık": "Der Betrag, den Sie senden, wird berechnet und Ihrem Konto im EUR-Gegenwert entsprechend dem aktuellen Wechselkurs gutgeschrieben.",
    "tlkarşılık": "Der Betrag, den Sie senden, wird berechnet und Ihrem Konto im TRY-Gegenwert entsprechend dem aktuellen Wechselkurs gutgeschrieben.",
    "sameacc": "Sie können kein Geld an dasselbe Konto senden.",
    "uhavent": "Sie haben kein solches Konto.",
    "rhesap": "Auf welches Konto möchten Sie Geld senden? (TRY/USD/EUR) | !WENN DAS KONTO, DAS SIE AUSWÄHLEN, DAS SELBE WIE DIE WÄHRUNG IST, DIE SIE DERZEIT VERARBEITEN, DRÜCKEN SIE 'ENTER'!:",
    "rusdno": "Der Empfänger hat kein USD-Konto.",
    "rnoeur": "Der Empfänger hat kein EUR-Konto."
}

